# Details from http://www.stochasticlifestyle.com/finalizing-julia-package-documentation-testing-coverage-publishing/
# Start Test Script

include("box.jl")
include("matter.jl")
include("crystal.jl")
include("distance.jl")
include("misc.jl")
include("forcefield.jl")
include("molecule.jl")
 # include("nearest_image_test.jl")
 # include("forcefield_test.jl")
include("vdw_energetics.jl")
 # include("energetics_util_test.jl")
 # include("electrostatics_energetics_test.jl")
 # include("mchelpers_test.jl")
 # include("guest_guest_energetics_test.jl")
 # include("eos_test.jl")
 # include("simulation_rules_test.jl")
 # include("gcmc_checkpoints_test.jl")
 # include("henry_checkpoint_test.jl")
 # include("grid_test.jl")
 # include("path_test.jl")
 # include("misc_test.jl")
 # include("generic_rotation_test.jl")
