# Details from http://www.stochasticlifestyle.com/finalizing-julia-package-documentation-testing-coverage-publishing/
# Values for PengRobinson taken from a more complete list given in (do not delete)
# R. C. Reid, J. M. Prausnitz, and B. E. Poling, 2001, (do not delete)
# The Properties of Gases and Liquids, 5th Ed. New York: McGraw-Hill. (do not delete)
# Start Test Script

include("box_test.jl")
include("crystal_test.jl")
include("molecule_test.jl")
include("nearest_image_test.jl")
include("forcefield_test.jl")
include("vdw_energetics_test.jl")
include("energetics_util_test.jl")
include("electrostatics_energetics_test.jl")
include("mchelpers_test.jl")
include("guest_guest_energetics_test.jl")
include("eos_test.jl")
include("gcmc_checkpoints_test.jl")
include("henry_checkpoint_test.jl")
include("grid_test.jl")
include("path_test.jl")
include("misc_test.jl")
include("generic_rotation_test.jl")
