#site_name:        PorousMaterials.jl
site_name:        ""
repo_url:         https://github.com/SimonEnsemble/PorousMaterials.jl
site_description: Documentation for the julia package PorousMaterials.jl
site_author:      SimonEnsemble

theme: windmill

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
  - mathjax-config.js

markdown_extensions:
  - pymdownx.arithmatex
  - extra
  - tables
  - fenced_code
  - toc:
      permalink: '#'
  #- toc:
  #    baselevel: 1
  #- mdx_math
extra:
  logo: assets/PMlogo.png


docs_dir: 'build'

pages:
  - PorousMaterials: index.md
  - Loading Data: guides/input_files.md
  - Manual:
    - Matter: manual/matter.md
    - Boxes, Crystals, and Grids: manual/boxes_crystals_grids.md
    - Molecules: manual/molecules.md
    - Atomic Interactions: manual/atomic_interactions.md
    - Molecular Simulations: manual/mof_simulations.md
    - Other: manual/other.md
  - FAQ: guides/faq.md
  - Help Wanted: guides/help_wanted.md
