name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  julia_version: '1.8.1'

jobs:

  unit-and-doc-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: checkout commit
        uses: actions/checkout@master

      - name: set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{env.julia_version}}
      
      - name: build package
        uses: julia-actions/julia-buildpkg@latest
      
      - name: install dependencies
        run: julia --project --color=yes -e 'import Pkg; Pkg.add.(["FIGlet", "Coverage"])'
      
      - name: run tests
        run: julia --project --color=yes --code-coverage -e 'import Pkg; Pkg.test(coverage=true)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      
      - name: process test coverage
        uses: julia-actions/julia-processcoverage@v1
      
      - name: upload coverage report
        uses: codecov/codecov-action@v2
        with:
          verbose: true


  aqua-jl:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: checkout commit
        uses: actions/checkout@v2

      - name: set up Julia
        uses: julia-actions/setup-julia@latest
        with:
          version: ${{ env.julia_version }}

      - name: build package
        uses: julia-actions/julia-buildpkg@latest

      - name: install dependencies
        run: julia --project --color=yes -e 'import Pkg; Pkg.add.(["Aqua"])'

      - name: Aqua.jl
        run: julia --project --color=yes ./test/aqua.jl
